version: "3.8"
services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9600:9600" # OpenSearch performance analyzer
    networks:
      - telyx-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    networks:
      - telyx-net
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - telyx-net
  
  otel-collector:
    image: otel/opentelemetry-collector:0.116.1
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./docker/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # gRPC
      - "55681:55681" # HTTP
    networks:
      - telyx-net
  
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    networks:
      - telyx-net

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    networks:
      - telyx-net

networks:
  telyx-net:
    driver: bridge
